[2024-03-28T02:46:24.369+0000] {processor.py:153} INFO - Started process (PID=349) to work on /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:46:24.392+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py for tasks to queue
[2024-03-28T02:46:24.419+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:46:24.418+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:46:26.799+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:46:26.784+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py", line 33, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:46:26.802+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:46:26.858+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py took 2.531 seconds
[2024-03-28T02:47:09.766+0000] {processor.py:153} INFO - Started process (PID=560) to work on /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:47:09.768+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py for tasks to queue
[2024-03-28T02:47:09.771+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:47:09.770+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:47:16.154+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:47:16.100+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py", line 33, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:47:16.167+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:47:16.216+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py took 6.465 seconds
[2024-03-28T02:48:11.461+0000] {processor.py:153} INFO - Started process (PID=807) to work on /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:48:11.467+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py for tasks to queue
[2024-03-28T02:48:11.471+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:48:11.471+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:48:15.477+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:48:15.470+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py", line 33, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:48:15.480+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:48:15.508+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py took 4.066 seconds
[2024-03-28T02:48:50.592+0000] {processor.py:153} INFO - Started process (PID=1021) to work on /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:48:50.596+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py for tasks to queue
[2024-03-28T02:48:50.598+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:48:50.598+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:48:51.979+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:48:51.973+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py", line 33, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:48:51.981+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:48:51.997+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py took 1.413 seconds
[2024-03-28T02:49:25.012+0000] {processor.py:153} INFO - Started process (PID=1243) to work on /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:49:25.017+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py for tasks to queue
[2024-03-28T02:49:25.020+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:49:25.020+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:49:26.801+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:49:26.790+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py", line 33, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:49:26.804+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:49:26.832+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py took 1.890 seconds
[2024-03-28T02:49:56.999+0000] {processor.py:153} INFO - Started process (PID=1442) to work on /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:49:57.001+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py for tasks to queue
[2024-03-28T02:49:57.003+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:49:57.003+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:49:58.651+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:49:58.644+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py", line 33, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:49:58.653+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:49:58.691+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py took 1.701 seconds
[2024-03-28T02:50:32.330+0000] {processor.py:153} INFO - Started process (PID=1654) to work on /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:50:32.337+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py for tasks to queue
[2024-03-28T02:50:32.341+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:50:32.340+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:50:36.545+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:50:36.509+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py", line 33, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:50:36.553+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:50:36.674+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py took 4.360 seconds
[2024-03-28T02:51:06.915+0000] {processor.py:153} INFO - Started process (PID=1860) to work on /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:51:06.916+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py for tasks to queue
[2024-03-28T02:51:06.918+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:51:06.918+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:51:07.972+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:51:07.968+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py", line 33, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:51:07.973+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:51:07.989+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py took 1.082 seconds
[2024-03-28T02:51:38.169+0000] {processor.py:153} INFO - Started process (PID=2069) to work on /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:51:38.170+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py for tasks to queue
[2024-03-28T02:51:38.172+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:51:38.171+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:51:39.178+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:51:39.176+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py", line 33, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:51:39.192+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:51:39.206+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py took 1.045 seconds
[2024-03-28T02:52:17.448+0000] {processor.py:153} INFO - Started process (PID=2291) to work on /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:52:17.451+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py for tasks to queue
[2024-03-28T02:52:17.454+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:52:17.454+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:52:19.140+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:52:19.134+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py", line 33, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:52:19.141+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:52:19.160+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py took 1.733 seconds
[2024-03-28T02:52:49.544+0000] {processor.py:153} INFO - Started process (PID=2509) to work on /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:52:49.547+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py for tasks to queue
[2024-03-28T02:52:49.549+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:52:49.548+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:52:50.856+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:52:50.838+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py", line 33, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:52:50.859+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:52:50.889+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py took 1.350 seconds
[2024-03-28T02:53:21.492+0000] {processor.py:153} INFO - Started process (PID=2715) to work on /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:53:21.494+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py for tasks to queue
[2024-03-28T02:53:21.495+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:53:21.495+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:53:22.249+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:53:22.242+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py", line 33, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:53:22.251+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:53:22.264+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py took 0.777 seconds
[2024-03-28T02:53:52.571+0000] {processor.py:153} INFO - Started process (PID=2926) to work on /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:53:52.572+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py for tasks to queue
[2024-03-28T02:53:52.573+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:53:52.573+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:53:53.283+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:53:53.280+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py", line 33, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:53:53.285+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:53:53.295+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py took 0.734 seconds
[2024-03-28T02:54:23.660+0000] {processor.py:153} INFO - Started process (PID=3140) to work on /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:54:23.661+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py for tasks to queue
[2024-03-28T02:54:23.663+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:54:23.662+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:54:24.405+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:54:24.402+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py", line 33, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:54:24.406+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:54:24.419+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py took 0.764 seconds
[2024-03-28T02:54:55.257+0000] {processor.py:153} INFO - Started process (PID=3351) to work on /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:54:55.258+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py for tasks to queue
[2024-03-28T02:54:55.259+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:54:55.259+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:54:56.103+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:54:56.100+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py", line 33, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:54:56.104+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:54:56.116+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py took 0.864 seconds
[2024-03-28T02:55:26.919+0000] {processor.py:153} INFO - Started process (PID=3567) to work on /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:55:26.921+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py for tasks to queue
[2024-03-28T02:55:26.923+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:55:26.922+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:55:27.809+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:55:27.807+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py", line 33, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:55:27.810+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:55:27.827+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py took 0.917 seconds
[2024-03-28T02:55:58.541+0000] {processor.py:153} INFO - Started process (PID=3789) to work on /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:55:58.543+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py for tasks to queue
[2024-03-28T02:55:58.544+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:55:58.544+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:55:59.571+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:55:59.568+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py", line 33, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:55:59.573+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:55:59.589+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py took 1.054 seconds
[2024-03-28T02:56:30.682+0000] {processor.py:153} INFO - Started process (PID=4000) to work on /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:56:30.685+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py for tasks to queue
[2024-03-28T02:56:30.687+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:56:30.687+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:56:31.639+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:56:31.635+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py", line 33, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:56:31.641+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py
[2024-03-28T02:56:31.657+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/Tasks/legacy_dags/ivy_cs.py took 0.985 seconds
